"""empty message

Revision ID: 909f3f067f23
Revises: 09228dca524f
Create Date: 2023-09-01 15:26:25.537916

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "909f3f067f23"
down_revision = "09228dca524f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_backends")
    with op.batch_alter_table("backends", schema=None) as batch_op:
        batch_op.add_column(sa.Column("primary_backend_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_backends_primary_backend_id_backends"),
            "backends",
            ["primary_backend_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backends", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_backends_primary_backend_id_backends"), type_="foreignkey"
        )
        batch_op.drop_column("primary_backend_id")

    op.create_table(
        "_alembic_tmp_backends",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("project_name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("type", sa.VARCHAR(length=30), nullable=False),
        sa.Column("config", sa.VARCHAR(length=2000), nullable=False),
        sa.Column("auth", sa.VARCHAR(length=2000), nullable=False),
        sa.Column("primary_backend_id", sa.INTEGER(), nullable=True),
        sa.Column("primary_backend_name", sa.VARCHAR(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_backend_id"],
            ["backends.id"],
            name="fk_backends_primary_backend_id_backends",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_name"],
            ["projects.name"],
            name="fk_backends_project_name_projects",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_backends"),
    )
    # ### end Alembic commands ###
